name: nightlight
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_glow: ^0.3.0
  page_transition: ^2.1.0
  provider: ^6.1.1
  assets_audio_player: ^3.1.1
  awesome_bottom_bar: ^1.2.4
  flex_color_picker: ^3.3.0
  syncfusion_flutter_sliders: ^24.1.43
  screen_brightness: ^0.2.2+1
  bubble_lens: ^2.0.0
  animated_background: ^2.0.0
  metaballs: ^1.5.0
  particle_field: ^1.0.0
  rnd: ^0.2.0
  particles_fly: ^0.0.8
  animate_gradient: ^0.0.2+1
  vitality: ^3.0.0
  funvas: ^0.1.8
  file_picker: ^6.1.1
  fluttertoast: ^8.2.4
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  flutter_countdown_timer: ^4.1.0
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  lottie: ^2.7.0
  url_launcher: ^6.2.2
  flutter_email_sender: ^6.0.2
  share_plus: ^7.2.1
  rating_dialog: ^2.0.4
  loading_animation_widget: ^1.2.0+4
  overlay_loader_with_app_icon: ^0.0.3
  firebase_remote_config: ^4.3.8
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  store_redirect: ^2.0.1
  firebase_messaging: ^14.7.10
  uuid: ^3.0.7
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InknutAntiqua-ExtraBold
      fonts:
        - asset: assets/fonts/InknutAntiqua-ExtraBold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Poppins-Regular.ttf
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Inter-VariableFont_slnt,wght.ttf
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: TradeWinds-Regular.ttf
      fonts:
        - asset: assets/fonts/TradeWinds-Regular.ttf
    - family: SpaceGrotesk-Regular.ttf
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
